---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/.github/workflows/requirements"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ansible-lint"
        update-types: ["version-update:semver-major"]
