---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "💣 Breaking Changes"
    labels:
      - "breaking change"
  - title: "🔔 Deprecation Warnings"
    labels:
      - "deprecation"
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🎉 Enhancements"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "📝 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
exclude-labels:
  - "skip-changelog"
version-resolver:
  minor:
    labels:
      - "breaking change"
      - "deprecation"
  patch:
    labels:
      - "bug"
      - "dependencies"
      - "documentation"
      - "feature"
      - "enhancement"
  default: patch
autolabeler:
  - label: "breaking change"
    body:
      - "/breaking/i"
  - label: "deprecation"
    branch:
      - "/deprecate\/.+/"
    title:
      - "/deprecate/i"
  - label: "feature"
    branch:
      - "/feat\/.+/"
      - "/feature\/.+/"
      - "/implement\/.+/"
    title:
      - "/feat/i"
      - "/feature/i"
      - "/implement/i"
  - label: "enhancement"
    branch:
      - "/add\/.+/"
      - "/enhancement\/.+/"
    title:
      - "/add/i"
      - "/enhancement/i"
  - label: "bug"
    branch:
      - "/fix\/.+/"
    title:
      - "/fix/i"
  - label: "documentation"
    branch:
      - "/docs\/.+/"
    files:
      - "**/!(changelog).md"
    title:
      - "/docs/i"
      - "/documentation/i"
  - label: "dependencies"
    files:
      - ".github/workflows/requirements/*"
template: |

  ## What's new in NGINX's Controller Agent Ansible role $RESOLVED_VERSION!

  $CHANGES

  ## Install & Upgrade

  *   To install the Ansible NGINX Controller Agent role on a fresh environment, run `ansible-galaxy install nginxinc.nginx_controller_agent`.
  *   To upgrade the Ansible NGINX Controller Agent role to the latest release, run `ansible-galaxy install -f nginxinc.nginx_controller_agent`.
  *   To install or upgrade to this specific Ansible NGINX Controller Agent role release ($RESOLVED_VERSION), run `ansible-galaxy install -f nginxinc.nginx_controller_agent,v$RESOLVED_VERSION`.

  ## Resources

  *   Functional configuration examples (check `converge.yml` under each `molecule` scenario) -- [github.com/nginxinc/ansible-role-nginx-config/tree/$RESOLVED_VERSION/molecule](https://github.com/nginxinc/ansible-role-nginx-config/tree/$RESOLVED_VERSION/molecule).
  *   Ansible Galaxy repository -- [galaxy.ansible.com/nginxinc/nginx](https://galaxy.ansible.com/nginxinc/nginx_controller_agent).
  *   NGINX: Better with Ansible demo -- [github.com/alessfg/nginx-ansible-demo](https://github.com/alessfg/nginx-ansible-demo).
