---
- name: Verify Mock
  hosts: mock_server
  connection: local
  tasks:
    - name: Check that the agent script request was sent to the mock controller exactly twice per docker instance (includes the idempotence test)
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/verify"
        method: PUT
        body:
          httpRequest:
            path: /install/controller-agent
          times:
            atLeast: 2
            atMost: 2
        status_code: 202
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false

- name: Verify File
  hosts: instances
  tasks:
    - name: Store the statistics of /etc/nginx/conf.d/nginx-plus-api.conf in the 'conf_file' variable
      stat:
        path: /etc/nginx/conf.d/nginx-plus-api.conf
      register: conf_file

    - name: Ensure /etc/nginx/conf.d/nginx-plus-api.conf exists
      assert:
        that: conf_file.stat.exists == true

    - name: Store the statistics of /var/log/nginx-controller/agent.log in the 'agent_log_file' variable
      stat:
        path: /var/log/nginx-controller/agent.log
      register: agent_log_file

    - name: Ensure /var/log/nginx-controller/agent.log exists
      assert:
        that: agent_log_file.stat.exists == true
